### PR TITLE
Development4

### PR DESCRIPTION
**Pull request by Peter-J-Freeman**

### CODE REVIEW

**Comment by Peter-J-Freeman** [comment]
@John-F-Wagstaff . I have added a rate limiter to the endpoints. It seems to work when spamming with locust, but I cannot seem to write tests to check it is working. Can you please review the code and think about how to test the limiters

**Comment by Peter-J-Freeman** [comment]
Hi @John-F-Wagstaff . How are the code changes for the tests going?

**Comment by John-F-Wagstaff** [comment]
Not ideal I was hoping to be finished already, I will try to get them done by the end of the day.

Do you want me to format them as comments for this code review, or as a patch? If you want a patch would you prefer I push the patch to this branch directly or make a sub-branch and pull request to Development4?

**Comment by Peter-J-Freeman** [comment]
Keep it simple. push to this branch directly.

**Comment by Peter-J-Freeman** [comment]
In a few days, I’ll get the db built and we can test. We need  COL1A1 NC_ descriptions upstream and downstream of the transcript boundaries since I know it has a NG_

Also, some descriptions withion some elements to test.


Dr Peter Freeman
Lecturer in Healthcare sciences (Clinical bioinformatics, genomics)
Division of Informatics, Imaging & Data Science
Faculty of Biology, Medicine and Health | The University of Manchester
G.725 | Stopford Building | Oxford Road | Manchester | M13 9PT
Tel: +44(0) 161 275 5731
email: ***@***.******@***.***>
web: Peter Freeman<https://www.research.manchester.ac.uk/portal/peter.j.freeman.html>
 [A close-up of a logo  Description automatically generated]
website: www.manchester.ac.uk<http://www.manchester.ac.uk/>
Social media:  Facebook<https://www.facebook.com/TheUniversityOfManchester> Twitter<https://twitter.com/OfficialUoM> LinkedIn<https://www.linkedin.com/school/university-of-manchester/> Instagram<https://www.instagram.com/officialuom/> YouTube<http://www.youtube.com/user/universitymanchester>

[VariantValidator Logo]
web: www.variantvalidator.org<http://www.variantvalidator.org/>
Social media: Twitter<https://twitter.com/intent/follow?ref_src=twsrc%5Etfw%7Ctwcamp%5Ebuttonembed%7Ctwterm%5Efollow%7Ctwgr%5EVariantValidatr&screen_name=VariantValidatr> Facebook<https://www.facebook.com/VariantValidator> Buy-us-a-coffee, supporting SWAN UK<https://www.buymeacoffee.com/VariantValidatr>




From: John-F-Wagstaff ***@***.***>
Date: Tuesday, 16 April 2024 at 12:03
To: openvar/rest_variantValidator ***@***.***>
Cc: Peter Freeman ***@***.***>, Author ***@***.***>
Subject: Re: [openvar/rest_variantValidator] Development4 (PR #173)

Not ideal I was hoping to be finished already, I will try to get them done by the end of the day.

Do you want me to format them as comments for this code review, or as a patch? If you want a patch would you prefer I push the patch to this branch directly or make a sub-branch and pull request to Development4?

**Comment by Peter-J-Freeman** [comment]
@John-F-Wagstaff I merged. Can you check your changes are now in master?

**Comment by John-F-Wagstaff** [comment]
what changes?

**Comment by Peter-J-Freeman** [comment]
Ah, my mistake. Thought you had pushed changed to tests, but you said you were going to push changes and tests l;ater. All good

**Pull request merged**
